name: Deploy Angular App

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
        architecture: 'x64'
        
    - name: Install dependencies
      run: |
        cd github-shortthirdman
        npm ci
      
    - name: Build Angular App
      run: |
        cd github-shortthirdman
        npm run build
      
    - name: Clone destination repository
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone --depth 1 https://github.com/shortthirdman/shortthirdman.github.io.git shortthirdman-github-io
      
    - name: Copy build artifacts
      run: |
        docs_dir="shortthirdman-github-io/docs"; if [ ! -d "$docs_dir" ]; then mkdir -p "$docs_dir"; echo "Directory '$docs_dir' created."; else echo "Directory '$docs_dir' already exists."; fi
        cp github-shortthirdman/dist/github-shortthirdman/3rdpartylicenses.txt ${docs_dir}/
        cp -R github-shortthirdman/dist/github-shortthirdman/browser/* ${docs_dir}/
      
    - name: Commit and push changes
      run: |
        cd shortthirdman-github-io
        git add .
        git commit -m "Auto deploy from main branch"
        git push origin main

    # - name: Email Notification
      # if: always()
      # uses: ad-m/github-push-action@0.8.0
      # with:
        # smtp-server: smtp.example.com
        # smtp-username: ${{ secrets.SMTP_USERNAME }}
        # smtp-password: ${{ secrets.SMTP_PASSWORD }}
        # to: swetank.mohanty@outlook.com
        # from: actions@github.com
        # subject: Deployment Successful
        # body: The deployment of the Angular app was successful.
