name: Latest Medium Blogs
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme
  packages: read
  statuses: write # To report GitHub Actions status checks
  actions: write # Needed for detection of GitHub Actions environment.
  id-token: write # Needed for provenance signing and ID.
  pull-requests: write

jobs:
  update-readme-with-blog:
    name: Update with latest Medium blogs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      # 1. NEW STEP: Import GPG key and configure Git to sign commits
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      
      - name: Configure Git
        run: |
          git config user.name "shortthirdman[bot]"
          git config user.email "swetank.mohanty@outlook.com"

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@1.9.6
        with:
          feed_names: "Medium"
          feed_list: "https://medium.com/feed/@shortthirdman,https://shortthirdman.medium.com/feed"
