name: Recent GitHub Activity
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:
jobs:
  update-recent-activity:
    name: Update this repository's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MAX_LINES: 10
